sudo: required
services:
- docker
language: go
go:
- 1.7.3
env:
  global:
  - secure: XZ9K5s30nKYgQXOkAaC5piXECScZFqzgRVgq3pzwVie3Qo8xTF0jdbrWkZGzLS/FulqV6YCLHd+FgORwVlQmjjJzciCBFdACqKFLu9b8Sg97S9up8YMXllKjsSFuuniW2jDYYS9V/gDEGFgAfb33+9SGYq4ORzZS7RBEeKfDJhXHGSaXUZIMavrhGRcA4lsoXqsT8BESabCd5QYm88tFDeSKh3+4BpBBZgHXC6G/EEKen8Z4701uCkgdV3nzqdLSVmGlcAC11xrIFwb+M4AZhlmuT52LAfOOBpc7cPFCkYQzmJlEsTxFF8wfRwou+ESETb5K0mUSVtE4aYh9W2jOEnh7sXfAIsXhSgjuQinGK3ZOrlD85sCz+vQWI9Fbw37Di3sEElV0zKP1VuD4OdTueJhwXjaWDVdhBJ6JVS7nixSnoJ3Cy0pCxKSLGEHvu9wzISHWax4BoLGqicNvHz4VRISttUpDjonWwX1JFKR+ZCYf0ul0jlhEb0WXdt/vdNirUekdySuU5imWYSg4dDkakIlv2CJeb46Aqx4DLGem++P6o51dDE0R7DtOmzS3NvTQ9pfp7aAIWRKFOooJVFOA3G99fUmbWxjNPWHlteUAHzlCdw7PSJmmBzOFBT4vn81M5TAIcO4QLR7FyOhjSY/V704YUiqyuP52bz1V2RYr+kI=
  - secure: PMXrUaNHEYsKSR4hMP1il/kMKeg4ILAsMrGnul3qqGUXl0abdwqsOxjdvb2H6eB56Wf+BiE8ESImdgC/SD0+JuSo6lVJe2y4NzkBoeJreT8Dks1otVEhz67/aCLJxJ1RcvHsHQDEsiYWYGk408jZzNGICasJbPgkBa8uRrhBw3f8t0StTpAXDGoZR0GpaIzKKAgD7+39J0lNfuWtEBzhoEXHSwYLQ7Wx167ya8HGnQ1FKlfQ9I8HMzW/h+8H46ydy1EwkwJuTXz+/63foVCzwXjdKRNLPNTtzk2fVddp3GAX2A6h2pLdgrg7imIdypfID2oqap/3wsZZFusfit38XhLIgbDNvF4l3y5CkhDG9ZpbPiLC283CmF6OqEvAjFMCzU545UcbjIn7b+uTtb4Z8iM1+tf0BRgoO1LnjGqwl056EPOn0vmu4MQs5KvZwINzzANOkqnGyCVZ7PVtNAVjyyzpHb6/XIkB4ly+y6JqehMT8aOgbmM99tgLs/Jr/aHwfB/g9UMo2d/bu6LLsGv27t+onYc8COfBC3abMaMxuSS+ZKJRnXw+nEquGuZZuQ6xmzboy2Y3jn/BEOKsIvz0lrTlwFplOj+ukbYulr2OH/44UGvvNhPYmO92w/m9mBMhTLWxN5xUVl7AjhONZ5zkLvcT8WA3ClLejDow0F0lAaE=
script:
- make test
- make build
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- make push
deploy:
  provider: releases
  api_key:
    secure: h4s9jisQ8H2WQbd/004vWpBDKGC21mspWdqqSJy8df2M7wH4d1XoC3jYkeSkK/KEPorWdvRiOhYfyfY4igWmo/4C/aPx6cl2R4MmKoC2vxATt1Fw7bamOTdcAcsHTgPyYdDgzfTqB2QY/RAWN5DAANAI7knCnradkrgIF5hoF4fJglwyAYN4AktK01MhJOWq9e+KrjhAQxE0oqhhCtHm7z8Z8E6oy5VZ35umcIDHc045WqTmEhTYXNwBa8fCHMYolalPCEAOw3yyeLzE9TW/HHbra4/bQc1n5t35CyBjxd9T3BGhKerzMszQzrUaqJri3prPTkkp8xt4xkMHnJFRcDLSA1SiC8/QcR2Y7QzzIBn4fWdzIFhQ8BE948VHgYAqWaNAFmcD5U+SOZUFNjYC44VQXcx6fEQUi6SA9g1X60rzg9dGUerqqK9HR7wFuZCuPIwLaaaMYhfjj5C9ndX20gmaJHx2QEkXbtySjBP+5wI1hmL2Uqqry9djnT6AZK+Ksnms/L4tYHgHk6zcXUpPGp7VVaOBbmgdBrK0ScRR6GRVhOSPxpIciADctlcj+w1qjJ30/VwdmnwZONAzYrNMknNNbdyMLOP4i3SzO+QsM3hj6c+y4UFJunzGNYfVKfKoJc01LylMWDGRquGf1ttoBkNfan46Q3TP2RdCahN2W1I=
  file: authz-webhook-amd64
  on:
    tags: true
